name: Build and run tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install poetry dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Run tests
      run: |
        poetry run python -m unittest discover